
#
# Product identity
#
CONFIG_ELENIX_WATCH_MARKETING_NAME="Elenix Watch"
CONFIG_ELENIX_WATCH_MODEL_NUMBER="S2508(0)"
# end of Product identity

#
# Build & Compilation
#
CONFIG_EOS_COMPILE_MODE_DEBUG=y
# CONFIG_EOS_COMPILE_MODE_RELEASE is not set
# CONFIG_EOS_ICON_STR_BUILD_IN is not set
CONFIG_EOS_USE_VIRTUAL_DISPLAY=y
# end of Build & Compilation

#
# Memory
#
CONFIG_EOS_MEM_PROVIDER_STDLIB_CLIB=y
# CONFIG_EOS_MEM_PROVIDER_AUTO is not set
# CONFIG_EOS_MEM_PROVIDER_CUSTOM is not set
# CONFIG_EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE is not set
CONFIG_EOS_MEM_TRACK_ENABLE=y
# end of Memory

#
# Image cache
#
# CONFIG_EOS_CACHE_ENABLE is not set
# end of Image cache

#
# RTOS
#
CONFIG_EOS_RTOS_BARE_METAL=y
# CONFIG_EOS_RTOS_FREERTOS is not set
# CONFIG_EOS_RTOS_RTTHREAD is not set
# CONFIG_EOS_RTOS_POSIX is not set
# CONFIG_EOS_RTOS_CUSTOM is not set
# end of RTOS

#
# Font
#
# CONFIG_EOS_FONT_C_MULTI is not set
CONFIG_EOS_FONT_TTF=y
CONFIG_EOS_FONT_CFG_LARGE_SIZE=30
CONFIG_EOS_FONT_CFG_MEDIUM_SIZE=26
CONFIG_EOS_FONT_CFG_SMALL_SIZE=22
# CONFIG_EOS_FONT_TTF_DATA is not set
CONFIG_EOS_FONT_TTF_FILE=y
CONFIG_EOS_FONT_TTF_FILE_PATH="font.ttf"
# end of Font

#
# Display
#
CONFIG_EOS_DISPLAY_WIDTH=390
CONFIG_EOS_DISPLAY_HEIGHT=450
CONFIG_EOS_DISPLAY_RADIUS=80
CONFIG_EOS_DISPLAY_BRIGHTNESS_MIN=5
CONFIG_EOS_DISPLAY_BRIGHTNESS_MAX=100
# end of Display

#
# File system
#
CONFIG_EOS_SYS_ROOT_DIR="/"
CONFIG_EOS_FS_POSIX=y
# CONFIG_EOS_FS_FATFS is not set
# CONFIG_EOS_FS_LITTLEFS is not set
# CONFIG_EOS_FS_RTTHREAD is not set
# CONFIG_EOS_FS_CUSTOM is not set
CONFIG_EOS_FS_PATH_MAX=256
CONFIG_EOS_LVGL_FS_LETTER=90
# CONFIG_EOS_DFW_ENABLE is not set
# end of File system

#
# Language
#
CONFIG_EOS_LANG_EN=y
# CONFIG_EOS_LANG_ZH is not set
# end of Language

#
# Logging
#
CONFIG_EOS_USE_ASSERT=y
# CONFIG_EOS_LOG_USE_COLOR is not set
CONFIG_EOS_LOG_MAX_LISTENERS=8
CONFIG_EOS_LOG_ENABLE_STD=y
# end of Logging

#
# Miscellaneous
#
CONFIG_EOS_ENABLE_TEST_APP=y
# end of Miscellaneous
