
#
# Product identity
#
CONFIG_ELENIX_WATCH_MARKETING_NAME="Elenix Watch"
CONFIG_ELENIX_WATCH_MODEL_NUMBER="S2508(0)"
# end of Product identity

#
# Build & Compilation
#
CONFIG_EOSCFG_COMPILE_MODE_DEBUG=y
# CONFIG_EOSCFG_COMPILE_MODE_RELEASE is not set
CONFIG_EOS_COMPILE_MODE=0
# CONFIG_EOS_ICON_STR_BUILD_IN is not set
CONFIG_EOS_USE_VIRTUAL_DISPLAY=y
# end of Build & Compilation

#
# Memory
#
CONFIG_EOSCFG_MEM_STDLIB=y
# CONFIG_EOSCFG_MEM_AUTO is not set
# CONFIG_EOSCFG_MEM_CUSTOM is not set
CONFIG_EOS_MEM_ALLOC_PROVIDER=0
# CONFIG_EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE is not set
CONFIG_EOS_MEM_TRACK_ENABLE=y
CONFIG_EOS_MEM_TRACK_TABLE_SIZE=4096
# end of Memory

#
# Image cache
#
CONFIG_EOS_CACHE_ENABLE=y
CONFIG_EOS_CACHE_SIZE=524288
CONFIG_EOS_CACHE_HEADER_COUNT=16
# CONFIG_EOS_CACHE_USE_DEDICATED_MEM is not set
# end of Image cache

#
# RTOS
#
CONFIG_EOSCFG_RTOS_BARE_METAL=y
# CONFIG_EOSCFG_RTOS_FREERTOS is not set
# CONFIG_EOSCFG_RTOS_RTTHREAD is not set
# CONFIG_EOSCFG_RTOS_POSIX is not set
# CONFIG_EOSCFG_RTOS_CUSTOM is not set
CONFIG_EOS_RTOS_TYPE=0
# end of RTOS

#
# Font
#
# CONFIG_EOSCFG_FONT_C_MULTI is not set
CONFIG_EOSCFG_FONT_TTF=y
CONFIG_EOS_FONT_TYPE=1
CONFIG_EOS_FONT_CFG_LARGE_SIZE=30
CONFIG_EOS_FONT_CFG_MEDIUM_SIZE=26
CONFIG_EOS_FONT_CFG_SMALL_SIZE=22
# CONFIG_EOSCFG_FONT_TTF_DATA is not set
CONFIG_EOSCFG_FONT_TTF_FILE=y
CONFIG_EOS_FONT_TTF_TYPE=1
CONFIG_EOS_FONT_TTF_FILE_PATH="font.ttf"
# CONFIG_EOS_FONT_TTF_ENABLE_EXTENDED is not set
# end of Font

#
# Display
#
CONFIG_EOS_DISPLAY_WIDTH=390
CONFIG_EOS_DISPLAY_HEIGHT=450
CONFIG_EOS_DISPLAY_RADIUS=80
CONFIG_EOS_DISPLAY_BRIGHTNESS_MIN=5
CONFIG_EOS_DISPLAY_BRIGHTNESS_MAX=100
# end of Display

#
# Platform Ports
#
CONFIG_EOS_PORT_MACOS_VOLUME_CONTROL_ENABLE=y
# end of Platform Ports

#
# File system
#
CONFIG_EOS_SYS_ROOT_DIR="/"
CONFIG_EOSCFG_FS_POSIX=y
# CONFIG_EOSCFG_FS_FATFS is not set
# CONFIG_EOSCFG_FS_LITTLEFS is not set
# CONFIG_EOSCFG_FS_RTTHREAD is not set
# CONFIG_EOSCFG_FS_CUSTOM is not set
CONFIG_EOS_FS_TYPE=0
CONFIG_EOS_FS_PATH_MAX=256
CONFIG_EOS_LVGL_FS_LETTER=90
# CONFIG_EOS_DFW_ENABLE is not set
# end of File system

#
# Language
#
CONFIG_EOSCFG_LANG_EN=y
# CONFIG_EOSCFG_LANG_ZH is not set
CONFIG_EOS_CONFIG_DEFAULT_LANGUAGE=0
# end of Language

#
# Logging
#
CONFIG_EOS_USE_ASSERT=y
# CONFIG_EOS_LOG_USE_COLOR is not set
CONFIG_EOS_LOG_MAX_LISTENERS=8
CONFIG_EOS_LOG_ENABLE_STD=y
# end of Logging

#
# Recent Apps
#
CONFIG_EOS_RECENT_APPS_ENABLE=y
CONFIG_EOS_RECENT_APPS_MAX=3
CONFIG_EOS_RECENT_APPS_MEM_HIGH_WATERMARK=2621440
CONFIG_EOS_RECENT_APPS_TIMER_RUN_ONCE=y
# CONFIG_EOS_RECENT_APPS_TIMER_RUN_ALL is not set
# CONFIG_EOS_RECENT_APPS_TIMER_SKIP is not set
CONFIG_EOS_RECENT_APPS_TIMER_STRATEGY=0
CONFIG_EOS_RECENT_APPS_ANIM_CONTINUE=y
# CONFIG_EOS_RECENT_APPS_ANIM_JUMP_TO_END is not set
CONFIG_EOS_RECENT_APPS_ANIM_STRATEGY=0
# end of Recent Apps

#
# Miscellaneous
#
CONFIG_EOS_ENABLE_TEST_APP=y
# end of Miscellaneous
