#!/usr/bin/env python3
"""
ElenixOS Kconfig management tool.

Usage:
  python scripts/kconfig.py menuconfig <directory> [--config <file>]
  python scripts/kconfig.py genconfig <config_dir> <output_file> [--defaults <file>]

menuconfig – launch curses-based configuration TUI.
             Reads/writes <directory>/.config by default.
             Use --config to specify a custom config file path.

genconfig   – merge Kconfig defaults → project defaults → build-dir .config,
              write eos_config_gen.h to <output_file>.
"""

import os
import sys
import tempfile
from kconfiglib import Kconfig, Symbol, BOOL, TRISTATE, INT, HEX, STRING
from menuconfig import menuconfig as _menuconfig_tui


KCONFIG_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "Kconfig"))
CHAR_LITERAL_SYMS = set()


def _symbol_value(sym: Symbol):
    if sym.type in (BOOL, TRISTATE):
        return 1 if sym.tri_value == 2 else 0
    elif sym.type == INT:
        v = sym.str_value
        return int(v) if v else 0
    elif sym.type == HEX:
        v = sym.str_value
        return v if v else "0x0"
    elif sym.type == STRING:
        return sym.str_value if sym.str_value else ""
    return 0


def _quote(name: str, val) -> str:
    s = str(val)
    if isinstance(val, int):
        return s
    if not s:
        return '""'
    if s.startswith('"') and s.endswith('"'):
        return s
    if s.startswith("'") and s.endswith("'"):
        return s
    if name in CHAR_LITERAL_SYMS:
        return f"'{s}'"
    return f'"{s}"'


def _load_config_file(kconfig: Kconfig, path: str, label: str):
    """Load a single config file with replace=True (higher priority wins)."""
    if os.path.exists(path):
        kconfig.load_config(path, replace=True)
        print(f"  Loaded {label}: {path}")
    else:
        print(f"  ⚠ {label} not found: {path}")


def generate(kconfig: Kconfig, outpath: str):
    lines = [
        "/*",
        " * Automatically generated by scripts/kconfig.py – DO NOT EDIT.",
        " * Source: Kconfig (ElenixOS core + simulator platform)",
        " */",
        "",
        "#ifndef EOS_CONFIG_GEN_H",
        "#define EOS_CONFIG_GEN_H",
        "",
    ]

    for sym in kconfig.unique_defined_syms:
        name = sym.name
        val = _symbol_value(sym)
        lines.append(f"#ifndef {name}")
        if isinstance(val, int):
            lines.append(f"#define {name} {val}")
        else:
            lines.append(f"#define {name} {_quote(name, val)}")
        lines.append(f"#endif")

    lines.append("")
    lines.append("#endif /* EOS_CONFIG_GEN_H */")
    lines.append("")

    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    new_content = "\n".join(lines) + "\n"
    try:
        with open(outpath) as f:
            if f.read() == new_content:
                return
    except FileNotFoundError:
        pass
    with open(outpath, "w") as f:
        f.write(new_content)

    print(f"→ Generated {outpath} ({len(kconfig.unique_defined_syms)} symbols)")


def _autoconf_outdir(workdir: str):
    """Return the generated/ subdir if workdir looks like a build tree."""
    candidate = os.path.join(workdir, "generated")
    return candidate if os.path.isdir(candidate) else None


def _usage():
    print(__doc__)
    sys.exit(1)


def main():
    if len(sys.argv) < 3:
        _usage()

    cmd, cfgdir = sys.argv[1], sys.argv[2]

    kconfig = Kconfig(KCONFIG_PATH)

    if cmd == "menuconfig":
        # Parse optional --config <file>
        custom_config = None
        args = sys.argv[3:]
        i = 0
        while i < len(args):
            if args[i] == "--config" and i + 1 < len(args):
                custom_config = args[i + 1]
                i += 2
            else:
                i += 1

        if custom_config:
            dotconfig = os.path.abspath(custom_config)
        else:
            dotconfig = os.path.abspath(os.path.join(cfgdir, ".config"))

        os.makedirs(os.path.dirname(dotconfig) or ".", exist_ok=True)
        _load_config_file(kconfig, dotconfig, "config file")

        with tempfile.NamedTemporaryFile(mode="w", suffix=".config", delete=False) as tmp:
            tmppath = tmp.name
        # Persist loaded config to the temp file so menuconfig shows saved
        # values instead of Kconfig defaults.
        kconfig.write_config(tmppath)
        os.environ["KCONFIG_CONFIG"] = tmppath
        _menuconfig_tui(kconfig)
        del os.environ["KCONFIG_CONFIG"]
        os.unlink(tmppath)

        kconfig.write_config(dotconfig)
        print(f"→ Saved {dotconfig}")

        if not custom_config:
            outdir = _autoconf_outdir(cfgdir)
            if outdir:
                generate(kconfig, os.path.join(outdir, "eos_config_gen.h"))
            else:
                print(f"→ Run 'cmake -B build' to regenerate eos_config_gen.h")

    elif cmd == "genconfig":
        outfile = sys.argv[3] if len(sys.argv) > 3 else os.path.join(cfgdir, "eos_autoconf.h")

        # Parse optional --defaults <file> before the positional args
        defaults = None
        args = sys.argv[4:]
        i = 0
        while i < len(args):
            if args[i] == "--defaults" and i + 1 < len(args):
                defaults = args[i + 1]
                i += 2
            else:
                i += 1

        # Priority (each step uses replace=True, so last one wins):
        #   1. Kconfig built-in defaults (lowest)
        #   2. Project defaults file (committed, overrides Kconfig)
        #   3. Build-dir .config (highest, user overrides from menuconfig)
        if defaults:
            _load_config_file(kconfig, defaults, "project defaults")

        dotconfig = os.path.join(cfgdir, ".config")
        _load_config_file(kconfig, dotconfig, "build-dir .config")

        generate(kconfig, outfile)

    else:
        _usage()


if __name__ == "__main__":
    main()
